export const enum HeroIcons {
    CHECK = 'i-heroicons-check',
    CLOCK = 'i-heroicons-clock',
    HOME = 'i-heroicons-home',
    LANGUAGE = 'i-heroicons-globe-alt',
    MAIL = 'i-heroicons-envelope',
    SEARCH = 'i-heroicons-magnifying-glass',
    BURGER_MENU = 'i-heroicons-bars-3',
    CLOSE = 'i-heroicons-x-mark',
    DOWN = 'i-heroicons-chevron-down',
    UP = 'i-heroicons-chevron-up',
    PASSWORD = 'i-heroicons-lock-closed',
    CHAT = 'i-heroicons-chat-bubble-left-ellipsis',
    SEND = 'i-heroicons-paper-airplane',
    VIDEO = 'i-heroicons-video-camera',
    PAUSE = 'i-heroicons-pause',
    START = 'i-heroicons-play',
    PHOTO = 'i-heroicons-photo',
    EYE = 'i-heroicons-eye',
    EYE_CLOSE = 'i-heroicons-eye-slash',
    FILE = 'i-heroicons-document',
    USER = 'i-heroicons-user',
    PLUS = 'i-heroicons-plus',
    HAND = 'i-heroicons-hand-thumb-up',
    ARROW_UP = 'i-heroicons-arrow-up',
  }